# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdSdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdSdkDemo
  pod 'AppLovinSDK'
  pod "FluctSDK"

  target 'AdSdkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdSdkDemoUITests' do
    # Pods for testing
  end

end
